{% set name = "slicerator" %}
{% set version = "1.0.0" %}
{% set sha256 = "047b10658527b9b12c9a0b9fc13f51e83c0620074db223e07e47b93b4cf1abae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/soft-matter/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - slicerator

about:
  home: http://github.com/soft-matter/slicerator
  license: BSD 3-Clause
  license_file: LICENSE
  summary: A lazy-loading, fancy-sliceable iterable
